// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VulnData.DataCollector.Domain;

#nullable disable

namespace VulnData.DataCollector.Domain.Persistance.Migrations
{
    [DbContext(typeof(VulnContext))]
    [Migration("20250330120935_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VulnData.DataCollector.Infrastructure.Models.BduData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<double>("Cvss2")
                        .HasColumnType("float");

                    b.Property<double>("Cvss3")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fixes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasEliminated")
                        .HasColumnType("bit");

                    b.Property<bool>("HasExploit")
                        .HasColumnType("bit");

                    b.Property<bool>("HasIncidents")
                        .HasColumnType("bit");

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VulnClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WayToDestroy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WayToFix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BduData");
                });

            modelBuilder.Entity("VulnData.DataCollector.Infrastructure.Models.BduData", b =>
                {
                    b.OwnsOne("VulnData.DataCollector.Infrastructure.Models.Cwe", "Cwe", b1 =>
                        {
                            b1.Property<string>("BduDataId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BduDataId");

                            b1.ToTable("BduData");

                            b1.WithOwner()
                                .HasForeignKey("BduDataId");
                        });

                    b.OwnsOne("VulnData.DataCollector.Infrastructure.Models.Vendor", "Vendor", b1 =>
                        {
                            b1.Property<string>("BduDataId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BduDataId");

                            b1.ToTable("BduData");

                            b1.WithOwner()
                                .HasForeignKey("BduDataId");
                        });

                    b.Navigation("Cwe")
                        .IsRequired();

                    b.Navigation("Vendor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
