services:
  postgres:
    image: postgres:16
    container_name: postgrescollector
    environment:
      POSTGRES_DB: collector
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
