// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VulnData.DataCollector.Domain;

#nullable disable

namespace VulnData.DataCollector.Domain.Persistance.Migrations
{
    [DbContext(typeof(VulnContext))]
    [Migration("20250411205654_add-nvd")]
    partial class addnvd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VulnData.DataCollector.Infrastructure.Models.Bdu.BduData", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<double>("Cvss2")
                        .HasColumnType("float");

                    b.Property<double>("Cvss3")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1300)
                        .HasColumnType("nvarchar(1300)");

                    b.Property<string>("Fixes")
                        .IsRequired()
                        .HasMaxLength(32800)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasEliminated")
                        .HasColumnType("bit");

                    b.Property<bool>("HasExploit")
                        .HasColumnType("bit");

                    b.Property<bool>("HasIncidents")
                        .HasColumnType("bit");

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasMaxLength(13500)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OtherId")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("OtherInfo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasMaxLength(32800)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VulnClass")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("WayToDestroy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("WayToFix")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("BduData");
                });

            modelBuilder.Entity("VulnData.DataCollector.Infrastructure.Models.Epss.EpssData", b =>
                {
                    b.Property<string>("Cve")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<double?>("Epss")
                        .HasColumnType("float");

                    b.Property<double?>("Percentile")
                        .HasColumnType("float");

                    b.HasKey("Cve");

                    b.ToTable("EpssData");
                });

            modelBuilder.Entity("VulnData.DataCollector.Persistance.Models.Nvd.NvdData", b =>
                {
                    b.Property<string>("Cve")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<double>("Cvss2")
                        .HasColumnType("float");

                    b.Property<double>("Cvss3")
                        .HasColumnType("float");

                    b.Property<double>("Cvss4")
                        .HasColumnType("float");

                    b.Property<string>("Cwe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cve");

                    b.ToTable("NvdData");
                });

            modelBuilder.Entity("VulnData.DataCollector.Infrastructure.Models.Bdu.BduData", b =>
                {
                    b.OwnsOne("VulnData.DataCollector.Infrastructure.Models.Bdu.Cwe", "Cwe", b1 =>
                        {
                            b1.Property<string>("BduDataId")
                                .HasColumnType("nvarchar(14)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(330)
                                .HasColumnType("nvarchar(330)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.HasKey("BduDataId");

                            b1.ToTable("BduData");

                            b1.WithOwner()
                                .HasForeignKey("BduDataId");
                        });

                    b.OwnsOne("VulnData.DataCollector.Infrastructure.Models.Bdu.Vendor", "Vendor", b1 =>
                        {
                            b1.Property<string>("BduDataId")
                                .HasColumnType("nvarchar(14)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(14500)
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(350)
                                .HasColumnType("nvarchar(350)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(450)
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasMaxLength(32800)
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BduDataId");

                            b1.ToTable("BduData");

                            b1.WithOwner()
                                .HasForeignKey("BduDataId");
                        });

                    b.Navigation("Cwe")
                        .IsRequired();

                    b.Navigation("Vendor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
